Add net-wireless/qt-dab-6.10-r1
- based on commit d42813517159e7b49cbccad5f3fd8fc043bc5c03 to include
  some fixes after tag 6.10
- set CMAKE_BUILD_TYPE="Release" as the default of "RelWithgDebInfo"
  fails to compile with errors like:
  "undefined reference to `vtable for circularButton'"